# numpy  is a module which contain many inbuild functions

# a[2,3] ---> bydefault 2nd row & 3rd columns

In [ ]:
#numpy use for-->
 1- arthmetic operation
 2-stats operation
 3-bitwise operator
 4-copy 7 view array
 5-stacking
 6-matrix
 7-linear algebra
 8-broadcasting
 9-math operation
 10- search,sorting counting

# numpy crash course

In [21]:
import numpy as np

In [23]:
np.version

<module 'numpy.version' from 'C:\\Users\\Asus\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [25]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# create array

In [28]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [30]:
type(my_list)

list

# below code we are converting list to array

In [33]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [35]:
type(arr)

numpy.ndarray

In [37]:
type(my_list)

list

In [ ]:
np.

In [39]:
np.arange(10)# it will return valus between 0 to  10 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(3.0)# it will  return in float numbers

array([0., 1., 2.])

In [43]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [45]:
np.arange(10,20)# it will return the values between the numbers we assign

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
np.arange(20,10) # it much be lessthen second argument , it will project empty array

array([], dtype=int32)

In [53]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [55]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [57]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [59]:
np.arange(10,20,5)

array([10, 15])

In [61]:
np.zeros(10)# bydefault it print in float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
np.zeros(5, dtype=int)# by the syntax we can change the value.

array([0, 0, 0, 0, 0])

# parameter tunning -- system uses his own parameter

In [71]:
np.zeros((2,2),dtype=int)# this is 2d array.

array([[0, 0],
       [0, 0]])

In [73]:
np.zeros((2,10))# it prints 2 rows& 10 colums

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [75]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [79]:
np.zeros((10,10),dtype=int)# this is Nd array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [81]:
np.ones(3)

array([1., 1., 1.])

In [83]:
np.ones((3),dtype=int)

array([1, 1, 1])

In [89]:
random.rand(3,2)

NameError: name 'random' is not defined

In [95]:
np.random.rand(5)# it will shuffle the numbers.

array([0.56349146, 0.33794689, 0.81284473, 0.29123857, 0.13665669])

In [103]:
np.random.rand(3,5)

array([[0.2798661 , 0.41262993, 0.36174161, 0.034808  , 0.23622247],
       [0.21205421, 0.55991837, 0.03741352, 0.95924308, 0.67626408],
       [0.6275828 , 0.52904578, 0.82161833, 0.42398615, 0.82609727]])

In [105]:
np.random.rand(4)

array([0.19042268, 0.29151131, 0.97246906, 0.7721051 ])

In [110]:
np.random.randint(4,6)

5

In [112]:
np.random.randint(10,20)

19

In [126]:
np.random.randint(10,20,4)# every time numbers will shuffle
# and it will only interprit just 3 numbers

array([13, 12, 16, 19])

In [130]:
np.random.randint(10,20,5)

array([11, 14, 10, 15, 11])

In [138]:
np.random.randint(10,40,(10,10))# generate the elements 10-3- with 4*4 matrix

array([[10, 30, 33, 34, 30, 30, 18, 26, 27, 14],
       [22, 31, 22, 22, 19, 23, 25, 24, 36, 32],
       [16, 12, 31, 27, 30, 35, 14, 21, 39, 32],
       [36, 20, 32, 33, 26, 37, 31, 12, 11, 28],
       [22, 12, 30, 10, 20, 11, 18, 22, 21, 18],
       [11, 22, 38, 10, 28, 17, 30, 15, 29, 31],
       [27, 13, 37, 32, 35, 27, 20, 37, 26, 25],
       [22, 35, 20, 21, 23, 34, 36, 19, 14, 38],
       [34, 21, 12, 11, 19, 29, 35, 35, 30, 19],
       [22, 25, 14, 29, 38, 27, 15, 22, 15, 33]])

In [ ]:
#numpy introduction
#numpy usecase 
#text,audio,image,number,xm,---must convert to array
#arange()
#zeros()
#ones()
#np.random.rand()
#np.random.randint()

In [144]:
np.arange(1,13).reshape(3,4)# if we have to reshape the numbers.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [156]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [158]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# slicing in matrix

In [171]:
a= np.random.randint(10,20,(5,4))
a

array([[18, 17, 17, 19],
       [13, 18, 18, 17],
       [19, 15, 15, 19],
       [10, 11, 12, 16],
       [12, 19, 10, 14]])

In [173]:
type(a)

numpy.ndarray

In [175]:
a

array([[18, 17, 17, 19],
       [13, 18, 18, 17],
       [19, 15, 15, 19],
       [10, 11, 12, 16],
       [12, 19, 10, 14]])

In [179]:
a[:]

array([[18, 17, 17, 19],
       [13, 18, 18, 17],
       [19, 15, 15, 19],
       [10, 11, 12, 16],
       [12, 19, 10, 14]])