# Array Creation Function

In [3]:
import numpy as np

In [5]:
# create an array from a list
a = np.array([1,2,3,4])
print("Array a:",a)

Array a: [1 2 3 4]


In [7]:
# create an array with early spaced values
b = np.arange(0,10,2)
print("Array b:",b)

Array b: [0 2 4 6 8]


In [11]:
#create an array with linearly spaced values
c = np.linspace(0,1,5)
print("Array c:",c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [13]:
#create an array filled with zeros
d =  np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
#create an identity matrix
f = np.eye(4)
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manipulation Function

In [22]:
# Reshape an array 
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [26]:
# Flatten an array 
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)
print("Flattened array:",flattened)

Flattened array: [1 2 3 4]


In [28]:
# Transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:\n",transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [30]:
# Stack arrays vertically
a2 = np.array([1,2])
b2 = np.array([4,5])
stacked = np.vstack([a2,b2])
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [[1 2]
 [4 5]]


# 3.Mathematical Function

In [80]:
# Add two arrays
g = np.array([1,2,3,4,5])
added = np.add(g,2)
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6 7]


In [82]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16 25]


In [84]:
# square root of each element
sqrt_val = np.sqrt(g)
print("Square root of g:",sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.         2.23606798]


In [48]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4 5]


In [60]:
# DOT  product of two arrays
a2 = np.array([1,2,3,4,5])
dot_product = np.dot(a2,g)
print("Dot product of a and g:", dot_product)

Dot product of a and g: 55


In [86]:
print(a)
print(a1)

[1 2 3 4]
[1 2 3]


# 4. Statistical Functions

In [93]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [95]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:",std_dev)

Standard deviation of s: 1.118033988749895


In [97]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:",minimum)

Min of s: 1


In [99]:
# Maximum element of an array
maximum = np.max(s)
print("Maximum of s:",maximum)

Maximum of s: 4


# Linear Algebra Functions

In [104]:
# Create a matrix
matrix = np.array([[1,2],[3,4]])

In [108]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:",determinant)

Determinant of matrix: -2.0000000000000004


In [110]:
# Inverse of matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n",inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 6. Random Sampling Functions

In [113]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)
print("Random value:",random_vals)

Random value: [0.06276385 0.24898612 0.71534195]


In [115]:
# Set seed for reproducibility
np.random.seed(0)
# Generate random values between 0 and 1 
random_vals = np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [117]:
# Generate random integers
rand_ints = np.random.randint(0,10,size = 5)
print("Random values:",rand_ints)

Random values: [3 7 9 3 5]


In [119]:
# Set seed for reproducibility
np.random.seed(0)
# Generate  random inetegers
rand_ints = np.random.randint(0,10,size=5)
print("Random values:",rand_ints)

Random values: [5 0 3 3 7]


# 7. Boolean & Logical Functions

In [124]:
#Check if all elements are True
# all
logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [128]:
# Check if any elements are True
logical_test = np.array([False,False,False])
all_true = np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [130]:
# check if any elements are True
# any 
any_true = np.any(logical_test)
print("Any elements True:",any_true)

Any elements True: False


# 8.Set Operations

In [133]:
# Intersection of two arrays
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a,set_b)
print("Intersection of a and  b:",intersection)

Intersection of a and  b: [3 4]


In [135]:
#Union of two arrays
union = np.union1d(set_a,set_b)
print("Union of a and b:",union)

Union of a and b: [1 2 3 4 5 6]


# 9.Array Attribute Functions

In [138]:
# Array attribution
a = np.array([1,2,3])
shape = a.shape # shape of the array
size = a.size # size of the array
dimentions = a.ndim # number of dimentions
dtype = a.dtype # data type of the array

print("Shape of the array:",shape)
print("Size  of the array:",size)
print("Number of dimentions of  array:",dimentions)
print("Data type of the array:",dtype)

Shape of the array: (3,)
Size  of the array: 3
Number of dimentions of  array: 1
Data type of the array: int32


# 10.Other Functions

In [141]:
# create a copy of an array 
a = np.array([1,2,3])
copied_array = np.copy(a)# create a copy of array a 
print("Copied of a:",copied_array)

Copied of a: [1 2 3]


In [143]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes #size in bytes
print("Size of a in bytes:",array_size_in_bytes)

Size of a in bytes: 12


In [153]:
# chexk if two arrays share memory
shared = np.shares_memory(a,copied_array)
print("Do a and copied_array share memor>",shared)

Do a and copied_array share memor> False
